/* v5.99.15 r12: immediate cached launch, bounded installs, visible update status. */
const CACHE='iocl-portal-shell-v5.99.15-r38';
const ROOT=new URL('./',self.location.href),APP=new URL('index.html',ROOT).href;
const FILES=['index.html','manifest.webmanifest','icon-192.png','icon-512.png','apple-touch-icon.png','icon-maskable-512.png','pipeline-module.b64','schedule-module.b64'].map(p=>new URL(p,ROOT).href);
async function note(text,done=false,error=false,percent=null){const all=await self.clients.matchAll({includeUncontrolled:true,type:'window'});all.forEach(c=>c.postMessage({update54:true,text,done,error,percent}));}
async function fetch54(u){const controller=new AbortController(),t=setTimeout(()=>controller.abort(),20000);try{const r=await fetch(u,{cache:'reload',signal:controller.signal});const bytes=await r.arrayBuffer();return new Response(bytes,{status:r.status,statusText:r.statusText,headers:r.headers})}finally{clearTimeout(t)}}
self.addEventListener('install',e=>e.waitUntil((async()=>{try{const c=await caches.open(CACHE);let done=0;await note('Update under progress... 0%',false,false,0);let next=0;await Promise.all(Array.from({length:3},async()=>{while(next<FILES.length){const index=next++;const u=new URL(FILES[index]);u.searchParams.set('apprev',CACHE);const r=await fetch54(u.href);if(!r.ok)throw Error('App file unavailable');await c.put(FILES[index],r);done++;const percent=Math.floor(done/FILES.length*100);await note('Update under progress... '+percent+'%',false,false,percent)}}));await note('Update under progress... 100%',true,false,100)}catch(x){await caches.delete(CACHE);await note('Update could not finish. Current version and saved work are kept. Reopen online to retry.',true,true);throw x}})()));
self.addEventListener('activate',e=>e.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('iocl-portal-shell-')&&k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim()})()));
self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(e.request.method!=='GET'||u.origin!==ROOT.origin)return;const shell=e.request.mode==='navigate'&&(u.pathname===ROOT.pathname||u.href===APP);if(!shell&&!FILES.includes(u.href))return;const key=shell?APP:u.href;e.respondWith((async()=>{const c=await caches.open(CACHE),cached=await c.match(key);if(cached)return cached;try{const r=await fetch54(e.request);if(!r.ok)throw Error('File unavailable');await c.put(key,r.clone());return r}catch(x){return new Response(shell?'<!doctype html><meta name="viewport" content="width=device-width"><body style="font:18px system-ui;padding:30px;background:#f5f8fc;color:#143d70"><h1>App update is taking too long</h1><p>Check your internet and try again. Your saved records are kept. Do not clear app storage.</p><button onclick="location.reload()" style="padding:12px">Try opening again</button></body>':'Module not available. Reopen online and retry.',{status:503,headers:{'Content-Type':shell?'text/html':'text/plain'}})}})());});

self.addEventListener('message',e=>{if(e.data?.activate74)self.skipWaiting()});
