/* v5.99.15 r12: immediate cached launch, bounded installs, visible update status. */
const CACHE='iocl-portal-shell-v5.99.15-r55';
const HASHES148={"apple-touch-icon.png":"57907d512a141fbf20c43a5742e2fc5f4b2821ecaa533e82b29082291aaf4698","icon-maskable-512.png":"c2e93dc235eb284855769a0d37daba8a86d79b2dfa2b3414dea6f48699d7bb92","schedule-module.b64":"5bbaca0e9e51e7c9a2e61e8c8f8cca3aae4bb13217027579d2fd0735fa163d03","manifest.webmanifest":"283a329ad8f8683ed55c94ddd034c0a6020143a831197fd445b929355f4aed56","index.html":"b975e0e2dc5b1b27a420650f2b30dd68a517850eb37844e6ed3a662d1883315b","pipeline-module.b64":"33424c1d4fc6335fe32f603398d232d46ff9fdf36b320da65be7678c7958adad","icon-192.png":"44805d488ec57e7269f182f65d8e02a5de286123b84dbdd769825a7a88228358","icon-512.png":"838ced7a5be902adfecdc7c6cb7d6c74815ee1debaec969dd13170d536344ce0"};
const ROOT=new URL('./',self.location.href),APP=new URL('index.html',ROOT).href;
const FILES=['index.html','manifest.webmanifest','icon-192.png','icon-512.png','apple-touch-icon.png','icon-maskable-512.png','pipeline-module.b64','schedule-module.b64'].map(p=>new URL(p,ROOT).href);
async function note(text,done=false,error=false,percent=null){const all=await self.clients.matchAll({includeUncontrolled:true,type:'window'});all.forEach(c=>c.postMessage({update54:true,text,done,error,percent}));}
async function fetch54(u){const controller=new AbortController(),t=setTimeout(()=>controller.abort(),20000);try{const r=await fetch(u,{cache:'reload',signal:controller.signal});const bytes=await r.arrayBuffer();return new Response(bytes,{status:r.status,statusText:r.statusText,headers:r.headers})}finally{clearTimeout(t)}}
self.addEventListener('install',e=>e.waitUntil((async()=>{try{const c=await caches.open(CACHE);let done=0;await note('Update under progress... 0%',false,false,0);let next=0;await Promise.all(Array.from({length:3},async()=>{while(next<FILES.length){const index=next++;const u=new URL(FILES[index]);u.searchParams.set('apprev',CACHE);let r=null;const keys=await caches.keys();for(const key of keys.filter(k=>k.startsWith('iocl-portal-shell-')&&k!==CACHE).reverse()){const previous=await caches.open(key),meta=await previous.match(new URL('__asset_hashes148',ROOT).href);if(meta){const hashes=await meta.json(),name=new URL(FILES[index]).pathname.split('/').pop();if(hashes[name]===HASHES148[name]){r=await previous.match(FILES[index]);if(r)break;}}}if(!r){r=await fetch54(u.href);if(!r.ok)throw Error('App file unavailable');const bytes=await r.clone().arrayBuffer(),digest=await crypto.subtle.digest('SHA-256',bytes),hash=[...new Uint8Array(digest)].map(n=>n.toString(16).padStart(2,'0')).join(''),name=new URL(FILES[index]).pathname.split('/').pop();if(hash!==HASHES148[name])throw Error('Published files are not ready yet');}if(!r.ok)throw Error('App file unavailable');await c.put(FILES[index],r);done++;const percent=Math.floor(done/FILES.length*100);await note('Update under progress... '+percent+'%',false,false,percent)}}));await c.put(new URL('__asset_hashes148',ROOT).href,new Response(JSON.stringify(HASHES148),{headers:{'Content-Type':'application/json'}}));await note('Update under progress... 100%',true,false,100)}catch(x){await caches.delete(CACHE);await note('Update could not finish. Current version and saved work are kept. Reopen online to retry.',true,true);throw x}})()));
self.addEventListener('activate',e=>e.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('iocl-portal-shell-')&&k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim()})()));
self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(e.request.method!=='GET'||u.origin!==ROOT.origin)return;const shell=e.request.mode==='navigate'&&(u.pathname===ROOT.pathname||u.href===APP);if(!shell&&!FILES.includes(u.href))return;const key=shell?APP:u.href;e.respondWith((async()=>{const c=await caches.open(CACHE),cached=await c.match(key);if(cached)return cached;try{const r=await fetch54(e.request);if(!r.ok)throw Error('File unavailable');await c.put(key,r.clone());return r}catch(x){return new Response(shell?'<!doctype html><meta name="viewport" content="width=device-width"><body style="font:18px system-ui;padding:30px;background:#f5f8fc;color:#143d70"><h1>App update is taking too long</h1><p>Check your internet and try again. Your saved records are kept. Do not clear app storage.</p><button onclick="location.reload()" style="padding:12px">Try opening again</button></body>':'Module not available. Reopen online and retry.',{status:503,headers:{'Content-Type':shell?'text/html':'text/plain'}})}})());});

self.addEventListener('message',e=>{if(e.data?.activate74)self.skipWaiting()});
